# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
base: &base
  working_directory: ~/hello-monorepo
  docker:
    - image: circleci/node:8.4.0

version: 2
jobs:
  a_build:
    <<: *base
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - a

  a_test:
    <<: *base
    steps:
      - attach_workspace:
          at: .

      - run:
          name: 'test a'
          command: |
            cd a
            yarn test

  a_tag:
    <<: *base
    steps:
      - checkout

      - add_ssh_keys

      - run:
          name: 'tag a'
          command: |
            git tag a -f
            git push --tags -f

  a_deploy:
    <<: *base
    steps:
      - checkout

      - add_ssh_keys

      - run:
          name: 'deploy a'
          command: git push "https://'':${API_TOKEN}@git.heroku.com/monorepo-a.git" HEAD:master

workflows:
  version: 2
  main:
    jobs:
      - a_build
      - a_test:
          requires:
            - a_build
      - a_tag:
          requires:
            - a_test
          filters:
            branches:
              only: master
  service_a:
    jobs:
      - a_hold:
          type: approval
          filters:
            tags:
              only: a
            branches:
              ignore: /.*/

      - a_deploy:
          requires:
            - a_hold
          filters:
            tags:
              only: a
            branches:
              ignore: /.*/

